// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgiuKNKuT_t6zycDUOK4itkdkLDNWaQCw',
    appId: '1:132829579017:web:5e9e3b2be3999c60fa75d8',
    messagingSenderId: '132829579017',
    projectId: 'project-3c33f',
    authDomain: 'project-3c33f.firebaseapp.com',
    storageBucket: 'project-3c33f.firebasestorage.app',
    measurementId: 'G-L7YS558LN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3L3AthV0eg0hZ-3KTNXZQWri882F-o24',
    appId: '1:132829579017:android:13bd9e80747a38c8fa75d8',
    messagingSenderId: '132829579017',
    projectId: 'project-3c33f',
    storageBucket: 'project-3c33f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9wKSACgBHPxG647uShASHV1z_hHr1dEQ',
    appId: '1:132829579017:ios:804d5479dca0db93fa75d8',
    messagingSenderId: '132829579017',
    projectId: 'project-3c33f',
    storageBucket: 'project-3c33f.firebasestorage.app',
    iosBundleId: 'com.example.projectProgramming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9wKSACgBHPxG647uShASHV1z_hHr1dEQ',
    appId: '1:132829579017:ios:804d5479dca0db93fa75d8',
    messagingSenderId: '132829579017',
    projectId: 'project-3c33f',
    storageBucket: 'project-3c33f.firebasestorage.app',
    iosBundleId: 'com.example.projectProgramming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgiuKNKuT_t6zycDUOK4itkdkLDNWaQCw',
    appId: '1:132829579017:web:65354b7b37511dadfa75d8',
    messagingSenderId: '132829579017',
    projectId: 'project-3c33f',
    authDomain: 'project-3c33f.firebaseapp.com',
    storageBucket: 'project-3c33f.firebasestorage.app',
    measurementId: 'G-E4V3P7Y83R',
  );
}
